### ISSUE TITLE
can I build the engine from a local model.

### ISSUE THREAD

**Issue by yyyanyy** [ddPn08/Lsmith#18]
I had download some model that is not shared on the huggingface, so can I build the engine from a local model?

**Comment by ddPn08** [comment]
If the model is diffusers format, local ones can also be used.

**Comment by koukei46124** [comment]
どのようにすれば良いでしょうか…？
modelIDにローカスのパスを入力しても動きません
![SnapCrab_NoName_2023-2-9_19-46-45_No-00](https://user-images.githubusercontent.com/78602544/217791326-ac80b7ac-ae7e-4529-822c-e3fd58a92d2c.png)

**Comment by ddPn08** [comment]
@koukei46124 ターミナルのログ見せてもらえますか？

**Comment by koukei46124** [comment]
![SnapCrab_NoName_2023-2-9_20-4-3_No-00](https://user-images.githubusercontent.com/78602544/217795672-9ce68c03-3ded-4612-9aba-4d1108078429.png)
![SnapCrab_NoName_2023-2-9_20-4-11_No-00](https://user-images.githubusercontent.com/78602544/217795688-821cf68b-d026-492c-9e58-c18dc2b5540f.png)
![SnapCrab_NoName_2023-2-9_20-4-58_No-00](https://user-images.githubusercontent.com/78602544/217795714-c72d144f-9fae-4542-bc68-e26e52c52fe0.png)

**Comment by koukei46124** [comment]
こんな感じです

**Comment by ddPn08** [comment]
これはdockerコンテナ内だからですね。基本的にdockerコンテナ内からwindowsのフォルダすべてにはアクセスできません（パスの形式もwindowsの物は使えないです。）
たとえばdocker-compose.ymlを
```
version: '3.9'
services:
  lsmith:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.lite
    ports:
      - 8000:8000
    volumes:
      - ./docker-data/models:/app/models
      - ./docker-data/outputs:/app/outputs
      - ./docker-data/diffusers:/diffusers
    environment:
      - COMMANDLINE_ARGS=--skip-build-frontend
      - UVICORN_ARGS=--host 0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
とすることでwindows上の`./docker-data/diffusers`がDockerコンテナ内の`/diffusers`にリンクします。
